version: "3.8"

networks:
  matchaid-network:
    driver: bridge

services:
  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.stats()"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - matchaid-network
  seeding:
    build:
      context: .
      dockerfile: Dockerfile.seed
    env_file:
      - ./.env
      - ./.env.local
    networks:
      - matchaid-network

volumes:
  mongodb_data_container:
